### ISSUE TITLE
dotween namespaces errors, probably related to missing dotween's dlls

### ISSUE THREAD

**Issue by maxnut** [AmaliJD/ManiaDash#2]
when trying to open the project, a bunch of errors related to dotween namespaces come up. at first i thought it was an engine version issue, but even after opening it with the correct version, these errors still come up.
![image](https://github.com/AmaliJD/ManiaDash/assets/54683950/13a69e9c-e731-4cbc-b97c-1ff8c031e115)
i'm assuming it's related to this issue since i dont see dotween dlls anywhere in the project
![image](https://github.com/AmaliJD/ManiaDash/assets/54683950/1a5855b9-4a56-40be-9a72-dd856254f4a3)
actually the dll seems to be there so i don't know what this issue might be related to

**Comment by AmaliJD** [comment]
I believe this is actually caused by not having git lfs installed on your machine, so not all the project files are getting downloaded. If you don't already have git lfs, you should install it, then clone the project again from scratch. If you do have git lfs already, I suppose you can download DoTween yourself for free from the asset store

**Comment by maxnut** [comment]
oh, i had no idea you needed that to use this project... maybe you should mention it in the readme. and yeah, i solved it by replacing dotween manually
